#! /bin/sh

. /home/ec2-user/.nvm/nvm.sh

set -x

if test "x$PRODUCTION_CREDENTIALS_PASSWORD" = x; then
  echo -n 'prod key: '
  read PRODUCTION_CREDENTIALS_PASSWORD
  export PRODUCTION_CREDENTIALS_PASSWORD
fi
APP_ENV=production PORT=80 PORT_SECURE=443 nohup npm start 2>&1 >> server.log &

